#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Build the miku-voicebank-pack1..packN Arch packages (.pkg.tar.zst).

The same voicebank, in pacman's format:

    sudo pacman -R miku-voicebank-pack

removes the Base package, and because every numbered pack depends on it pacman
takes them all down in one transaction.  Each package's `pre_remove` runs
`miku-show --tick --index N`: the first one hands the show to a background
conductor, the rest wait for their own moment in the song, so one package really
is erased every few seconds while pacman's progress bar climbs with the lyrics.

The archive is a zstd-compressed tar with .PKGINFO, .MTREE and .INSTALL.

    python3 tools/build_pkg.py                       # 51 packages into dist/
    python3 tools/build_pkg.py --count 100
    python3 tools/build_pkg.py --audio-url https://example.com/song.mp3
    python3 tools/build_pkg.py --audio 初音ミクの消失.flac
    python3 tools/build_pkg.py --fake-size 0

zstd is needed to compress: the python `zstandard` module if it is installed,
otherwise the `zstd` binary (present on any Arch box).  gzip is used as a last
resort, which pacman also accepts (it reads .pkg.tar.gz) - the build says which
one it picked.
"""

from __future__ import annotations

import argparse
import gzip
import hashlib
import io
import os
import shutil
import subprocess
import sys
import tarfile

HERE = os.path.dirname(os.path.abspath(__file__))
PACK_DIR = os.path.dirname(HERE)                        # miku-remove-pacman/
ROOT = PACK_DIR
sys.path.insert(0, HERE)

import common    # noqa: E402  (this project's own payload helpers)
import profiles  # noqa: E402  (this project's own vocabulary)

SRC = common.SRC
DIST = os.path.join(PACK_DIR, "dist")

PROFILE = "pacman"                     # pacman wording in the transcript

VERSION = common.show_version()
PKG_BASE = "miku-voicebank-pack"
PKG_BASE_ARCH = "miku-voicebank-pack"        # pacman allows the plain name
PACKAGER = "cosMo@暴走P <cosmo@bousou-p.invalid>"
HOMEPAGE = "https://www.bilibili.com/video/BV1zb8E6cE2a/"
LICENSE_TAG = "custom:MIT"

FAKE_TOTAL = int(5.4 * 1024 * 1024 * 1024)   # 5.4 GiB, as apt reports it


# --------------------------------------------------------------------------
# compression
# --------------------------------------------------------------------------

def compressor():
    """-> (name, callable(data) -> bytes).  zstd first, gzip as a fallback."""
    try:
        import zstandard  # type: ignore
    except ImportError:
        zstandard = None
    if zstandard is not None:
        def pack(data, _z=zstandard):
            cctx = _z.ZstdCompressor(level=19, write_checksum=True)
            return cctx.compress(data)
        return "zstd(python)", pack
    exe = shutil.which("zstd")
    if exe:
        def pack(data, _exe=exe):
            res = subprocess.run([_exe, "-19", "-T1", "-q", "-c", "--check"],
                                 input=data, stdout=subprocess.PIPE,
                                 stderr=subprocess.PIPE)
            if res.returncode != 0:
                raise RuntimeError("zstd failed: %s" % res.stderr.decode(
                    "utf-8", "replace"))
            return res.stdout
        return "zstd(%s)" % os.path.basename(exe), pack

    def pack(data):
        buf = io.BytesIO()
        with gzip.GzipFile(fileobj=buf, mode="wb", compresslevel=9,
                           mtime=common.MTIME) as gz:
            gz.write(data)
        return buf.getvalue()
    return "gzip(fallback)", pack


# --------------------------------------------------------------------------
# the pacman package format
# --------------------------------------------------------------------------

def pkg_info(name, size, desc, depends, optdepends, provides, backup=()) -> bytes:
    lines = [
        "pkgname = %s" % name,
        "pkgbase = %s" % name,
        "pkgver = %s-1" % VERSION,
        "pkgdesc = %s" % desc,
        "url = %s" % HOMEPAGE,
        "builddate = %d" % common.MTIME,
        "packager = %s" % PACKAGER,
        "size = %d" % size,
        "arch = any",
        "license = %s" % LICENSE_TAG,
    ]
    for dep in depends:
        lines.append("depend = %s" % dep)
    for dep in optdepends:
        lines.append("optdepend = %s" % dep)
    for provide in provides:
        lines.append("provides = %s" % provide)
    for path in backup:
        lines.append("backup = %s" % path)
    lines.append("")
    lines.append("# generated by miku-remove-pacman/tools/build_pkg.py")
    return ("\n".join(lines) + "\n").encode("utf-8")


def mtree(files, mtime=common.MTIME) -> bytes:
    """.MTREE: what `pacman -Qkk` checks the installed files against."""
    out = ["#mtree"]
    for path, data, mode in sorted(files, key=lambda f: f[0]):
        rel = path.strip("/")
        out.append("./%s time=%.1f mode=%o size=%d type=file md5digest=%s"
                   % (rel, float(mtime), mode, len(data),
                      hashlib.md5(data).hexdigest()))
    body = ("\n".join(out) + "\n").encode("utf-8")
    buf = io.BytesIO()
    with gzip.GzipFile(fileobj=buf, mode="wb", compresslevel=9,
                       mtime=mtime) as gz:
        gz.write(body)
    return buf.getvalue()


def pkg_tar(files, extra) -> bytes:
    """A tar with .PKGINFO/.INSTALL/.MTREE first, then the payload."""
    raw = io.BytesIO()
    with tarfile.open(fileobj=raw, mode="w", format=tarfile.GNU_FORMAT) as tar:
        for name, data in extra:
            info = tarfile.TarInfo("./" + name)
            info.size = len(data)
            info.mode = 0o644
            info.uid = info.gid = 0
            info.uname = info.gname = "root"
            info.mtime = common.MTIME
            tar.addfile(info, io.BytesIO(data))
        for path, data, mode in sorted(files, key=lambda f: f[0]):
            info = tarfile.TarInfo("./" + path.strip("/"))
            info.size = len(data)
            info.mode = mode
            info.uid = info.gid = 0
            info.uname = info.gname = "root"
            info.mtime = common.MTIME
            tar.addfile(info, io.BytesIO(data))
    return raw.getvalue()


PRE_REMOVE = """
pre_remove() {
    # $1 is "remove" when the package is really going away; it is "upgrade"
    # during a -Syu, and then nobody should be singing.
    [ "$1" = "remove" ] || return 0
    local show=/usr/share/miku-voicebank/bin/miku-show
    [ -x "$show" ] || return 0
    if command -v timeout >/dev/null 2>&1; then
        timeout 900 "$show" --tick --index __INDEX__ --count __COUNT__ || true
    else
        "$show" --tick --index __INDEX__ --count __COUNT__ || true
    fi
}
"""

POST_BASE = """post_install() {
    echo "[VOCALOID] 声库本体 miku-voicebank-pack (4.0) 已注册"
    # 歌曲如果是从网络获取的，就在后台先抓下来，卸载时不用等网络
    if [ -x /usr/share/miku-voicebank/bin/miku-show ]; then
        nohup /usr/share/miku-voicebank/bin/miku-show --fetch-audio --quiet \\
            >/dev/null 2>&1 &
    fi
}
"""

POST_BANNER = """post_install() {
cat <<'BANNER'

====================================
Top-level package installed (miku-voicebank-pack1)
Dependency chain: 1→2→3→…→__COUNT__→miku-voicebank-pack
Removing miku-voicebank-pack removes the whole voicebank.
====================================
BANNER
}
"""

POST_DATA = """post_install() {
    echo "[VOCALOID] 声库数据 pack__INDEX__ 已注册（__INDEX__/__COUNT__）"
}
"""


def install_script(index: int, count: int) -> bytes:
    """The pacman .INSTALL hooks, with __INDEX__/__COUNT__ stamped in."""
    if index == 0:
        header = (
            "#!/bin/sh\n"
            "# miku-voicebank-pack - pacman hooks\n"
            "#\n"
            "# 卸载时让声库唱完最后一首歌：本体的 pre_remove 把演出交给后台\n"
            "# conductor，然后一直等到整首歌唱完才返回（编号包只等自己那一拍）。\n")
        body = POST_BASE
    else:
        header = (
            "#!/bin/sh\n"
            "# miku-voicebank-pack__INDEX__ - pacman hooks\n"
            "#\n"
            "# 卸载时让声库唱完最后一首歌。每个包的 pre_remove 都会调用一次\n"
            "# miku-show，__INDEX__ 是本包在链条里的名次。\n")
        body = POST_BANNER if index == 1 else POST_DATA
    body = (header + body + PRE_REMOVE).replace("__INDEX__", str(index)).replace(
        "__COUNT__", str(count))
    return body.encode("utf-8")


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--count", type=int, default=common.PACK_COUNT)
    ap.add_argument("--version", default=VERSION)
    ap.add_argument("--out", default=DIST)
    ap.add_argument("--audio", default="",
                    help="local song file to ship inside the base package")
    ap.add_argument("--audio-url", default=common.DEFAULT_AUDIO_URL,
                    help="...or fetch the song from this URL at removal time")
    ap.add_argument("--offset", type=float, default=common.AUDIO_OFFSET)
    ap.add_argument("--fake-size", type=float, default=5.4,
                    help="GiB pacman should *claim* the package occupies")
    ap.add_argument("--profile", default=PROFILE,
                    help="package-manager vocabulary for the transcript "
                         "(deb | rpm | pacman)")
    ap.add_argument("--quiet", action="store_true")
    args = ap.parse_args()

    if not args.audio and not args.audio_url:
        default_song = os.path.join(ROOT, common.SONG_NAME)
        if os.path.isfile(default_song):
            args.audio = default_song
        else:
            sys.stderr.write("build_pkg: neither --audio nor --audio-url given\n")
            return 2

    audio_bytes = b""
    audio_name = ""
    if args.audio:
        if not os.path.isfile(args.audio):
            sys.stderr.write("build_pkg: song not found: %s\n" % args.audio)
            return 2
        audio_bytes = common.read(args.audio)
        audio_name = os.path.basename(args.audio)

    timeline = common.timeline_bytes(args.offset, args.profile)
    conf = common.conf_text(audio_name if audio_bytes else "", args.audio_url,
                            args.profile)
    readme = common.read_text(os.path.join(SRC, "doc", "README.md"))
    copyright_text = common.read_text(os.path.join(SRC, "doc", "copyright"))
    show = common.show_script()
    wrapper = common.wrapper_script()
    vocab_text = common.read_text(os.path.join(HERE, "profiles.py"))

    comp_name, compress = compressor()
    if not args.quiet:
        print("  compressor: %s" % comp_name)

    ext = ".pkg.tar.zst" if comp_name.startswith("zstd") else ".pkg.tar.gz"
    os.makedirs(args.out, exist_ok=True)
    fake_total = int(args.fake_size * 1024 * 1024 * 1024)
    per_fake = fake_total // (args.count + 1)
    total_bytes = 0

    for index in range(0, args.count + 1):
        files = []
        if index == 0:
            files.append(("usr/share/miku-voicebank/bin/miku-show", show, 0o755))
            files.append(("usr/share/miku-voicebank/bin/profiles.py",
                          vocab_text, 0o644))
            files.append(("usr/share/miku-voicebank/timeline.tsv", timeline, 0o644))
            if audio_bytes:
                files.append(("usr/share/miku-voicebank/audio/" + audio_name,
                              audio_bytes, 0o644))
            files.append(("usr/bin/miku-voicebank-show", wrapper, 0o755))
            files.append(("etc/miku-voicebank/show.conf", conf, 0o644))
            files.append(("usr/share/miku-voicebank/packs/pack0.dat",
                          common.voicebank_dat(0, args.count), 0o644))
            for path, size, mode in common.MEMORY_FILES:
                files.append((path.strip("/"),
                              common.memory_blob(path, size), mode))
            files.append(("usr/share/doc/%s/README.md" % PKG_BASE, readme, 0o644))
            files.append(("usr/share/doc/%s/copyright" % PKG_BASE,
                          copyright_text, 0o644))
            depends = ["python", "sh"]
            optdepends = ["mpv: play the song while the voicebank is removed",
                          "ffmpeg: alternative decoder", "mpg123: alternative decoder"]
            provides = ["%s=%s" % (PKG_BASE_ARCH, args.version)]
            backup = ["etc/miku-voicebank/show.conf"]
            desc = ("miku 4.0 voicebank (base package) - removing it plays "
                    "初音ミクの消失 while the files are deleted")
        else:
            files.append(("usr/share/miku-voicebank/packs/pack%d.dat" % index,
                          common.voicebank_dat(index, args.count), 0o644))
            depends = ["sh"]
            if index < args.count:
                depends.append("%s%d=%s" % (PKG_BASE_ARCH, index + 1, args.version))
            else:
                # an exact version: only the base package of this build
                # satisfies it, which is what keeps the chain in step
                depends.append("%s=%s" % (PKG_BASE_ARCH, args.version))
            optdepends = []
            provides = []
            backup = []
            desc = "miku 4.0 voicebank data pack (%d/%d)" % (index, args.count)

        name = common.pkg_name(index)
        install = install_script(index, args.count)
        real_size = sum(len(data) for _p, data, _m in files)
        info = pkg_info(name, real_size + per_fake, desc, depends, optdepends,
                        provides, backup)
        tree = mtree(files)
        tar = pkg_tar(files, [(".PKGINFO", info), (".INSTALL", install),
                              (".MTREE", tree)])
        data = compress(tar)

        filename = "%s-%s-1-any%s" % (name, args.version, ext)
        with open(os.path.join(args.out, filename), "wb") as f:
            f.write(data)
        total_bytes += len(data)
        if not args.quiet:
            sys.stdout.write("\r  built %3d/%d  %-52s %8.1f KiB"
                             % (index + 1, args.count + 1, filename, len(data) / 1024))
            sys.stdout.flush()

    if not args.quiet:
        print("\n  %d packages (%s + pack1..pack%d), %.1f MiB total"
              % (args.count + 1, PKG_BASE, args.count, total_bytes / 1048576))
        print("  chain: pack1 → … → pack%d → %s" % (args.count, PKG_BASE))
        print("  remove everything: sudo pacman -R %s" % PKG_BASE)
        print("  -> install with:   sudo pacman -U ./dist/*%s" % ext)
    return 0


if __name__ == "__main__":
    sys.exit(main())
