#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Payload shared by this project's builders.

The Debian, RPM and pacman projects are three independent copies of the same
joke, so the interesting parts - the show script, the lyric timeline, the
configuration, the fake voicebank memory images - are built here and used by
whatever package format this project produces.  Every path below is relative to
*this* project, so each copy stands on its own.

The lyrics themselves are not distributed: `miku-show` fetches the song from
`AUDIO_URL` and caches it.
"""

from __future__ import annotations

import hashlib
import io
import os
import random
import re
import sys

# <project>/tools/common.py -> <project>
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "src")

SHOW_SCRIPT = os.path.join(SRC, "bin", "miku-show")
WRAPPER_SCRIPT = os.path.join(SRC, "bin", "miku-voicebank-show")
CONF_TEMPLATE = os.path.join(SRC, "etc", "show.conf")
TIMELINE = os.path.join(SRC, "data", "timeline.tsv")
SRT = os.path.join(ROOT, "miku-remove.srt")

SONG_NAME = "初音ミクの消失.flac"
DEFAULT_AUDIO_URL = os.environ.get("MIKU_AUDIO_URL",
                                   "https://fms.uiero.com/downloads/mkrm.mp3")

PACK_COUNT = 51
AUDIO_OFFSET = 25.6
MTIME = 1234567890

KANA = ("あ い う え お か き く け こ さ し す せ そ た ち つ て と な に ぬ ね の "
        "は ひ ふ へ ほ ま み む め も や ゆ よ ら り る れ ろ わ を ん "
        "が ぎ ぐ げ ご ざ じ ず ぜ ぞ だ ぢ づ で ど ば び ぶ べ ぼ ぱ ぴ ぷ ぺ ぽ "
        "きゃ きゅ きょ しゃ しゅ しょ ちゃ ちゅ ちょ にゃ にゅ にょ りゃ りゅ りょ "
        "ヴ ファ フィ フェ フォ ティ ディ ツィ").split()

# the fake voicebank memory images, exactly as in the .deb build
MEMORY_FILES = (
    ("/usr/share/vocaloid/models/memory/r.-1.2.img", 5120, 0o644),
    ("/usr/share/vocaloid/models/memory/r.0.-1.img", 6144, 0o644),
    ("/usr/share/vocaloid/models/memory/r.0.0.img", 7168, 0o644),
    ("/usr/share/vocaloid/models/memory/r.0.1.img", 4096, 0o644),
    ("/usr/share/vocaloid/models/memory/r.1.-2.img", 5632, 0o644),
    ("/usr/share/vocaloid/models/memory/r.1.-3.img", 4608, 0o644),
    ("/usr/share/vocaloid/models/memory/user.img", 2048, 0o444),
    ("/usr/share/vocaloid/models/blobs/r.-1.2.img", 8192, 0o644),
)

DESC_TAIL = """
Hatsune Miku voicebank sample data, split over a dependency chain so that the
engine can stream it while it is being registered.
.
Everything depends on the base package `miku-voicebank-pack`, so removing that
one package takes the whole voicebank down with it.  Doing so invokes the
VOCALOID uninstaller, which is known to be a little dramatic about it.
"""


def read(path: str) -> bytes:
    with open(path, "rb") as f:
        return f.read()


def read_text(path: str) -> bytes:
    """Read a file that ends up in a package as text, and force LF."""
    if not os.path.isfile(path):
        return b""
    return read(path).replace(b"\r\n", b"\n").replace(b"\r", b"\n")


def show_version(default: str = "3.9.1") -> str:
    """The version miku-show reports, so packages and show never disagree."""
    try:
        with open(SHOW_SCRIPT, "r", encoding="utf-8") as f:
            m = re.search(r'^VERSION\s*=\s*"([^"]+)"', f.read(), re.M)
        return m.group(1) if m else default
    except OSError:
        return default


def show_script() -> bytes:
    return read_text(SHOW_SCRIPT)


def wrapper_script() -> bytes:
    return read_text(WRAPPER_SCRIPT)


def pkg_name(index: int, base: str = "miku-voicebank-pack") -> str:
    """index 0 = the base package, 1..N = the numbered data packs."""
    return base if index == 0 else "%s%d" % (base, index)


def conf_text(audio_path: str, audio_url: str, profile: str = "") -> bytes:
    text = read_text(CONF_TEMPLATE).decode("utf-8")
    text = (text.replace("__AUDIO__", audio_path)
                .replace("__AUDIO_URL__", audio_url)
                .replace("__PROFILE__", profile or ""))
    return text.encode("utf-8")


def timeline_bytes(offset: float = AUDIO_OFFSET, profile: str = "deb") -> bytes:
    """The lyric timeline, with the package manager's words stamped in.

    `make_timeline` leaves the system chatter as `<TOKEN>` placeholders (the
    source video was recorded on an Arch box, so its kernel line says `yay`);
    this expands them for the package being built, and keeps the tokens when the
    SRT is missing and the timeline ships as it is.
    """
    tool_path = os.path.join(ROOT, "tools")
    if tool_path not in sys.path:
        sys.path.insert(0, tool_path)
    import make_timeline
    import profiles

    prof = profiles.get(profile)
    if os.path.isfile(SRT):
        items = make_timeline.build(make_timeline.read_srt(SRT), offset)
        buf = io.StringIO()
        buf.write("# miku-voicebank lyric timeline - generated by "
                  "tools/make_timeline.py\n")
        buf.write("# source: %s  (song starts at %s in the source video)\n"
                  % (os.path.basename(SRT), make_timeline.SONG_START))
        buf.write("# audio offset: %+.3f s\n" % offset)
        buf.write("# start %.3f\n" % offset)
        buf.write("# total %.3f\n"
                  % (make_timeline.SONG_END - make_timeline.SONG_START))
        buf.write("# profile: %s (%s)\n" % (prof["name"], prof["family"]))
        buf.write("# t_enter\tkind\ttext\n")
        for t, kind, text in profiles.expand_lines(items, prof):
            buf.write("%.3f\t%s\t%s\n" % (t, kind, text))
        return buf.getvalue().encode("utf-8")

    # a source checkout ships the generated timeline: expand its placeholders
    text = read_text(TIMELINE).decode("utf-8")
    out = []
    for line in text.splitlines():
        if not line or line.startswith("#"):
            out.append(line)
        else:
            out.append(profiles.expand_line(line, prof))
    return ("\n".join(out) + "\n").encode("utf-8")


def voicebank_dat(index: int, count: int) -> bytes:
    """A plausible-looking slab of voicebank sample data."""
    rnd = random.Random(0xC05 + index)
    out = ["# miku-voicebank-pack%d  (%d/%d)" % (index, index, count),
           "# bank    : miku 4.0 (CV)",
           "# format  : 44.1 kHz / 16 bit / mono / RAW+FRQ",
           "# samples : %d" % (110 + index * 7),
           "#"]
    for i in range(110 + index * 7):
        syl = rnd.choice(KANA)
        dur = rnd.uniform(0.08, 0.62)
        size = int(dur * 88200)
        freq = rnd.choice((440.0, 466.2, 493.9, 523.3, 554.4, 587.3, 622.3, 659.3))
        out.append("%s_%03d.wav\t%.3f s\t%7d B\t%.1f Hz\t%s"
                   % (syl, i, dur, size, freq, rnd.choice(("frq", "raw", "raw+frq"))))
    return ("\n".join(out) + "\n").encode("utf-8")


_MEMO_CACHE = {}


def memory_blob(name: str, size: int) -> bytes:
    """Deterministic fake memory image (same bytes as the .deb build)."""
    if name in _MEMO_CACHE:
        return _MEMO_CACHE[name]
    # a stable seed: hash() is randomised per process, which would make two
    # builds of the same package differ
    seed = int(hashlib.md5(name.encode("utf-8")).hexdigest()[:8], 16)
    rnd = random.Random(seed)
    head = ("MIKU-MEMORY-IMAGE\t%s\tmiku 4.0\t--nosave\n"
            % os.path.basename(name)).encode("utf-8")
    body = bytes(rnd.getrandbits(8) for _ in range(max(0, size - len(head))))
    blob = head + body
    _MEMO_CACHE[name] = blob
    return blob
