#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Turn the fan-made SRT (a full "terminal transcript" of the meme video) into a
clean song-relative timeline for ``miku-show``.

Input : miku-remove.srt
Output: src/data/timeline.tsv   (t_enter <TAB> t_exit <TAB> kind <TAB> text)

The SRT is timed against a ~4:09 edit of the song which starts at 00:30.583
(the moment "正在删除 miku" begins).  We re-base every entry to song time and
apply AUDIO_OFFSET so the lyrics line up with the FLAC that actually ships with
the package (the 4:46 "LONG VERSION").

kind:
  lyric  normal lyric line            (white)
  voice  Miku talking to the master   (yellow, printed with a leading ">")
  sys    fake filesystem / kill / error spam
  note   section banners such as ＜最高速の离别之歌＞
"""
import argparse
import os
import re
import sys

# --- constants of the source video -----------------------------------------
SONG_START = 30.583      # SRT time where the song starts (deletion begins)
SONG_END = 279.816       # SRT time where the removal reaches 100% (/ 4:39.816)

ACCUM_GAP = 0.30         # >= this gap + prefix extension  -> typewriter line, keep only the longest
DUP_WINDOW = 0.60        # identical text closer than this  -> duplicate

SYS_RE = re.compile(
    r"^("
    r"删除失败|错误：|损坏:|损#|#坏|kill|A stop job|Operation aborted|"
    r"进程终止信号|正在尝试杀|\s*：正在尝试杀"
    r")"
)
STEP_RE = re.compile(r"^\(\d/\d\)")
APT_RE = re.compile(r"^::")

# The first bars of the source video draw the lyric on top of the fake progress
# bar ("(1/2) 正在删除 miku              [我诞生在这世上"), so those entries are
# unreadable as they are.  Reassemble the opening couplet by hand.
OVERLAY_DEBRIS = ("正在删除 miku", "生在这世上然后发觉到自己")
OPENING = [
    (31.383, "lyric", "我诞生在这世上 然后发觉到自己"),
    (32.033, "lyric", "自己只是 模仿着人类而已"),
]


def parse_time(t):
    h, m, rest = t.split(":")
    s, ms = rest.split(",")
    return int(h) * 3600 + int(m) * 60 + int(s) + int(ms) / 1000.0


def read_srt(path):
    with open(path, "r", encoding="utf-8-sig") as f:
        text = f.read()
    out = []
    for block in re.split(r"\n\s*\n", text.strip()):
        lines = block.splitlines()
        if len(lines) < 3 or "-->" not in lines[1]:
            continue
        a, b = lines[1].split("-->")
        out.append((parse_time(a.strip()), parse_time(b.strip()), "\n".join(lines[2:]).strip()))
    return out


def classify(text):
    if text.startswith(">"):
        return "voice", text.lstrip("> ").strip()
    if text.startswith("---"):
        return "note", text
    if SYS_RE.match(text):
        return "sys", text
    return "lyric", text


def build(entries, offset):
    items = []
    for start, end, raw in entries:
        t = start - SONG_START
        if t < -0.05 or t > SONG_END - SONG_START:
            continue
        text = raw.replace("\n", " ").strip()
        if not text or STEP_RE.match(text) or APT_RE.match(text):
            continue
        if any(d in text for d in OVERLAY_DEBRIS):
            continue
        kind, text = classify(text)
        items.append([max(t, 0.0), end - SONG_START, kind, text])

    for start, kind, text in OPENING:
        items.append([start - SONG_START, start - SONG_START + 1.0, kind, text])
    items.sort(key=lambda it: it[0])

    # drop "typewriter" duplicates: keep the longest of a progressive run
    cleaned = []
    for it in items:
        if cleaned:
            prev = cleaned[-1]
            same_kind = prev[2] == it[2]
            prefix = it[3].startswith(prev[3]) and len(it[3]) > len(prev[3])
            if same_kind and prefix and (it[0] - prev[0]) >= ACCUM_GAP:
                cleaned[-1] = it
                continue
            if same_kind and prev[3] == it[3] and (it[0] - prev[0]) < DUP_WINDOW:
                continue
        cleaned.append(it)

    # apply the audio alignment and never let two lines share a timestamp
    out = []
    last = -1.0
    for t, t_end, kind, text in cleaned:
        t = round(t + offset, 3)
        if t < 0:
            t = 0.0
        if t <= last:
            t = round(last + 0.05, 3)
        last = t
        out.append((t, kind, text))
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("srt")
    ap.add_argument("out")
    ap.add_argument("--offset", type=float, default=float(os.environ.get("MIKU_AUDIO_OFFSET", 0.0)),
                    help="seconds to add to every entry (audio alignment)")
    args = ap.parse_args()

    items = build(read_srt(args.srt), args.offset)
    os.makedirs(os.path.dirname(os.path.abspath(args.out)), exist_ok=True)
    with open(args.out, "w", encoding="utf-8", newline="\n") as f:
        f.write("# miku-voicebank lyric timeline - generated by tools/make_timeline.py\n")
        f.write("# source: miku-remove.srt  (song starts at %s in the source video)\n" % SONG_START)
        f.write("# audio offset: %+.3f s\n" % args.offset)
        f.write("# start %.3f\n" % args.offset)
        f.write("# total %.3f\n" % (SONG_END - SONG_START))
        f.write("# t_enter\tkind\ttext\n")
        for t, kind, text in items:
            f.write("%.3f\t%s\t%s\n" % (t, kind, text))
    counts = {}
    for _, k, _ in items:
        counts[k] = counts.get(k, 0) + 1
    sys.stderr.write("timeline: %d entries %s  (%.1fs .. %.1fs)\n"
                     % (len(items), counts, items[0][0] if items else 0, items[-1][0] if items else 0))


if __name__ == "__main__":
    main()
